```{r}
set.seed(1234)
mystat <- function(x, dist) {
    c(c(x),  # Bootstrap will return actual pseudo-sample, mean, and standard deviation
      MASS::fitdistr(x, dist)$estimate)
}
```

```{r}
mysim <- function(n, phi, blksize, B, dist, f) {

  if (phi == 0) {
    x <- rnorm(n)
  } else {
    x <- arima.sim(list(ar = phi), n = n) * sqrt(1 - phi^2)
  }
  emp <- ecdf(x)(sort(x)) # observed empirical distribution
  fit_theta <- MASS::fitdistr(x, dist)$estimate # observed fitted values
  fit <- do.call(f, c(list(sort(x)), as.list(fit_theta))) # observed fitted distribution
  obsv_ks <- sqrt(n) * max(abs(emp - fit)) # observed ks statistic
  bts <- boot::tsboot(x, mystat, l = blksize, sim = "fixed", R = B, dist = dist)
  list_cdf <- matrix(, nrow = 0, ncol = n) 
  # initialize list of each pseudo-sample's ecdf applied to original sample values
  list_theta <- matrix(, nrow = 0, ncol = 2) 
  # initialize list of each pseudo-sample's fitted theta
  # bts$t[i, (1:n)] : values of bootstrap sample
  # bts$t[i, -(1:n)] : theta (mu, and sigma)
  sum_theta <- 0
  for (i in 1:B) {
    list_cdf <- rbind(list_cdf, c(ecdf(bts$t[i, (1:n)])(sort(x))))
    list_theta <- rbind(list_theta, c(bts$t[i, -(1:n)]))
  }
  exp_emp_cdf <- colMeans(list_cdf)
  exp_theta <- colMeans(list_theta)
  exp_fit_cdf <- do.call(f, c(list(sort(x)), as.list(exp_theta)))
  bias_term <- exp_emp_cdf - exp_fit_cdf
  ks_values <- c()
  for (i in 1:B) {
    emp_cdf <- list_cdf[i,]
    fit_cdf <- do.call(f, c(list(sort(x)), as.list(list_theta[i, ])))
    ks_values <- c(ks_values, sqrt(n) * max(abs((emp_cdf - fit_cdf - bias_term))))
  }
  c(mean(ks_values > obsv_ks))
}

```

```{r}
n <- 200
phi <- -0.4
blksize <- 6
B = 1000
dist = 'normal'
f = pnorm
print(mysim(n, phi, blksize, B, dist, f))
```
```{r}
phi <- -0.4
d_n_0.4 <- replicate(1000, mysim(n, phi, blksize, B, dist, f))
hist(d_n_0.4)
```
```{r}
phi <- -0.2
d_n_0.2 <- replicate(1000, mysim(n, phi, blksize, B, dist, f))
hist(d_n_0.2)
```
```{r}
phi <- 0
(d_n_0 <- replicate(1000, mysim(n, phi, blksize, B, dist, f)))
hist(d_n_0)
```
```{r}
phi <- 0.2
(d_0.2 <- replicate(1000, mysim(n, phi, blksize, B, dist, f)))
hist(d_0.2)
```
```{r}
phi <- 0.4
(d_0.4 <- replicate(1000, mysim(n, phi, blksize, B, dist, f)))
hist(d_0.4)
```




